ComputerShop/ComputerShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComputerShop.Repositories;
using Microsoft.AspNetCore.Mvc;
using ComputerShop.Data.Models;

namespace ComputerShop.Controllers
{
    public class CategoryController:Controller
    {
        Context c = new Context();
        CategoryRepository categoryRepository = new CategoryRepository();
        public IActionResult Index(string p){
            
            if (!string.IsNullOrEmpty(p))
            {
                return View(categoryRepository.List(X=>X.CategoryName == p));
            }
            return View(categoryRepository.TList());
        }

        [HttpGet]
        public IActionResult CategoryAdd(){
           return View();
        }
        [HttpPost]
         public IActionResult CategoryAdd(Category p){
            if (!ModelState.IsValid)
            {
                return View("CategoryAdd");
            }
            categoryRepository.TAdd(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult CategoryDelete(int id)
        {
            categoryRepository.TDelete(new Category {CategoryID = id});
                return RedirectToAction("Index");
        }
        public IActionResult CategoryGet(int id){
            var x = categoryRepository.TGet(id);
            Category ct = new Category(){
                CategoryName=x.CategoryName,
                CategoryDescription=x.CategoryDescription,
                CategoryID=x.CategoryID
            };
            return View(ct);
        }
        [HttpPost]
        public IActionResult CategoryUpdate(Category p){
            var x = categoryRepository.TGet(p.CategoryID);
            x.CategoryID = p.CategoryID;
            x.CategoryName = p.CategoryName;
            x.CategoryDescription = p.CategoryDescription;
            x.Status = true;
            categoryRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
      

    }
}

ComputerShop/ComputerShop/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComputerShop.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace ComputerShop.Controllers
{
    public class ChartController:Controller
    {
        public IActionResult Index(){

            return View();
        }
        public IActionResult Index2(){
            return View();
        }
        public IActionResult  VisualizeProductResult(){
            return Json(ComputerList());//metodumun ismi
        }
        public List<Class1> ComputerList(){
            List<Class1> cs = new List<Class1>();
            using(var c = new Context()){
             cs=c.Computers.Select(x=>new Class1{
                 computername=x.Name,
                 stock=x.Stock
             }).ToList();
             }
             return cs;
        }
        public IActionResult Statistics(){
            Context c = new Context();
            //Computer Count
            var deger1 = c.Computers.Count();
            ViewBag.d1 = deger1;
            //Categories Count
            var deger2 = c.Categories.Count();
            ViewBag.d2 = deger2;
            //Computer Stock
            var deger3 = c.Computers.Sum(x=>x.Stock);
            ViewBag.d3 = deger3;
            //Average Price
            var deger5 = c.Computers.Average(X=>X.Price).ToString("0.00");
            ViewBag.d5 = deger5;
            return View();
        }
           
    }       
    
}

ComputerShop/ComputerShop/Controllers/ComputerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ComputerShop.Data.Models;
using ComputerShop.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ComputerShop.Controllers;
using X.PagedList;
using Microsoft.AspNetCore.Http;

namespace ComputerShop.Controllers
{
    public class ComputerController: Controller
    {
      Context c = new Context();
      ComputerRepository computerRepository = new ComputerRepository();
        public IActionResult Index(int page=1){
          
          return View(computerRepository.TList("Category").ToPagedList(page,5));
        }

        [HttpGet]
        public IActionResult ComputerAdd(){
          List<SelectListItem> Values = (from x in c.Categories.ToList()
                                    select new SelectListItem{
                                        Text = x.CategoryName,
                                        Value = x.CategoryID.ToString()
                                    }).ToList();
          ViewBag.Vls = Values;
          return View();
        }
        [HttpPost]
         public IActionResult ComputerAdd(Computer p){
           if (!ModelState.IsValid)
            {
                return View("ComputerAdd");
            }
            computerRepository.TAdd(p);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult ComputerDelete(int id){
          computerRepository.TDelete(new Computer {ComputerID = id});
          return RedirectToAction("Index");
        }
        public IActionResult ComputerGet(int id){
          var x = computerRepository.TGet(id);
          Computer d = new Computer(){
            ComputerID = x.ComputerID,
            CategoryID = x.CategoryID,
            Name=x.Name,
            Price = x.Price,
            Stock=x.Stock,
            Description=x.Description,
            ImageUrl=x.ImageUrl
          };
          List<SelectListItem> dp = (from c in c.Computers.ToList()
                                      select new SelectListItem{
                                        Text = c.Name,
                                        Value = c.ComputerID.ToString()
                                      }).ToList();
          ViewBag.dgr = dp;
          return View(d);
        }
        [HttpPost]
        public IActionResult ComputerUpdate(Computer p){
          var x = computerRepository.TGet(p.ComputerID);
            x.ComputerID = p.ComputerID;
            x.Name = p.Name;
            x.Price = p.Price;
            x.Stock = p.Stock;
            x.ImageUrl = p.ImageUrl;
            x.Description = p.Description;
            x.CategoryID = p.CategoryID;

            computerRepository.TUpdate(x);
          return RedirectToAction("Index");
        }

    }
}

ComputerShop/ComputerShop/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ComputerShop.Controllers
{
    public class DefaultController:Controller
    {
        [AllowAnonymous]
        public IActionResult Index(){

            return View();
        }
        [AllowAnonymous]
        public IActionResult CategoryDetails(int id){
            ViewBag.x = id;
            return View();
        }
    }
}

ComputerShop/ComputerShop/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using ComputerShop.Data.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ComputerShop.Controllers
{
    
    public class LoginController:Controller
    {
        Context c = new Context();
        [AllowAnonymous]
        public IActionResult Index(){
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Index(Admin p){
            var DataValue = c.Admins.FirstOrDefault(X=>X.UserName == p.UserName && X.Password == p.Password);

            if(DataValue != null){
                var claims = new List<Claim>{
                    new Claim(ClaimTypes.Name,p.UserName)
                };

                var useridentity = new ClaimsIdentity(claims,"Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index","Default");
            }  
            return View();
        }
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> LogOut(){
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index","Login");
        }
    }
}

ComputerShop/ComputerShop/Views/Category/CategoryAdd.cshtml
@model ComputerShop.Data.Models.Category
@{
    ViewData["Title"] = "CategoryAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CategoryAdd","Category",FormMethod.Post))
{
     <h3>Category Name</h3>
     @Html.TextBoxFor(x=>x.CategoryName, new {@class="form form-control"})
     @Html.ValidationMessageFor(x=>x.CategoryName,"",new {@style="color:red"})
     <br/>
     <h3>Category Description</h3>
     @Html.TextAreaFor(x=>x.CategoryDescription, new {@class="form form-control"})
     <br/>
     <button class="btn btn-success">Cattegory Add</button>
}

ComputerShop/ComputerShop/Views/Category/CategoryGet.cshtml
@model ComputerShop.Data.Models.Category
@{
    ViewData["Title"] = "CategoryGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("CategoryUpdate","Category",FormMethod.Post))
{
    <h3>Category ID</h3>
    @Html.TextBoxFor(x=>x.CategoryID, new {@class="form form-control"})
     <br/>
     <h3>Category Name</h3>
     @Html.TextBoxFor(x=>x.CategoryName, new {@class="form form-control"})
     @Html.ValidationMessageFor(x=>x.CategoryName,"",new {@style="color:red"})
     <br/>
     <h3>Category Description</h3>
     @Html.TextAreaFor(x=>x.CategoryDescription, new {@class="form form-control"})
     <br/>
     <button class="btn btn-success">Update</button>
}

ComputerShop/ComputerShop/Views/Category/Index.cshtml
@model List<ComputerShop.Data.Models.Category>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Category List</h2>
<br>
@using(Html.BeginForm()){
    <p>
        Category Name:@Html.TextBox("p")
        <input type="submit" value="Find"/>
    </p>
}
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Category Name</th>
        <th>Status</th>
        <th>Delete</th>
        <th>Update</th>
    </tr>
    @foreach (var x in Model)
    {
    <tr>
        <td>@x.CategoryID</td>
        <td>@x.CategoryName</td>
        <td>@x.Status</td>
        <td><a href="/Category/CategoryDelete?id=@x.CategoryID" class="btn btn-danger">Delete</a></td>
        <td><a href="/Category/CategoryGet?id=@x.CategoryID" class="btn btn-success">Update</a></td>
    </tr>        
    }
</table>
<a href="/Category/CategoryAdd/" class="btn btn-primary">New Category</a>

ComputerShop/ComputerShop/Views/Chart/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stocks');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.computername, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Computer - Stock",
                width: 1000,
                height: 750,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

ComputerShop/ComputerShop/Views/Chart/Index2.cshtml
@{
    ViewData["Title"] = "Index2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stocks');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.computername, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Computer - Stock",
                width: 1000,
                height: 750,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('ColumnChart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="ColumnChart_div"></div>
</body>
</html>

ComputerShop/ComputerShop/Views/Chart/Statistics.cshtml
@{
    ViewData["Title"] = "Deneme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <link href="~/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <script src="~/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Total Computer</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.d2</h3>
                    <p>Total Category</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">
              <div class="icon-text">
                    <h3>@ViewBag.d3</h3>
                    <p>Sum Stock Computer</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.d5$</h3>
                    <p>Average Price</p>
                </div>

                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


</body>
</html>

ComputerShop/ComputerShop/Views/Computer/ComputerAdd.cshtml
@model ComputerShop.Data.Models.Computer
@{
    ViewData["Title"] = "ComputerAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("ComputerAdd","Computer",FormMethod.Post))
{
     <h3>Computer Name</h3>
     @Html.TextBoxFor(x=>x.Name, new {@class="form form-control"})
     <br/>
     <h3>Computer Description</h3>
     @Html.TextAreaFor(x=>x.Description, new {@class="form form-control"})
     <br/>
     <h3>Computer Price</h3>
     @Html.TextBoxFor(x=>x.Price, new {@class="form form-control"})
     <br/>
     <h3>Computer Stock</h3>
     @Html.TextBoxFor(x=>x.Stock, new {@class="form form-control"})
     <br/>
     <h3>Computer İmage</h3>
     @Html.TextBoxFor(x=>x.ImageUrl, new {@class="form form-control"})
     <br/>
    <h3>Computer Category</h3>
     @Html.DropDownListFor(x=>x.CategoryID, (List<SelectListItem>) ViewBag.Vls, new {@class="form form-control"})
     <br/>
     <button class="btn btn-success">Computer Add</button>
}

ComputerShop/ComputerShop/Views/Computer/ComputerGet.cshtml
@model ComputerShop.Data.Models.Computer
@{
    ViewData["Title"] = "ComputerGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("ComputerUpdate","Computer",FormMethod.Post))
{
    <h3>Computer Id</h3>
     @Html.TextBoxFor(x=>x.ComputerID, new {@class="form form-control"})
     <br/>
     <h3>Computer Name</h3>
     @Html.TextBoxFor(x=>x.Name, new {@class="form form-control"})
     <br/>
     <h3>Computer Description</h3>
     @Html.TextAreaFor(x=>x.Description, new {@class="form form-control"})
     <br/>
     <h3>Computer Price</h3>
     @Html.TextBoxFor(x=>x.Price, new {@class="form form-control"})
     <br/>
     <h3>Computer Stock</h3>
     @Html.TextBoxFor(x=>x.Stock, new {@class="form form-control"})
     <br/>
     <h3>Computer İmage</h3>
     @Html.TextBoxFor(x=>x.ImageUrl, new {@class="form form-control"})
     <br/>
    <h3>Computer Category</h3>
     @Html.DropDownListFor(x=>x.CategoryID, (List<SelectListItem>) ViewBag.dgr, new {@class="form form-control"})
     <br/>
     <button class="btn btn-success">Update</button>
}

ComputerShop/ComputerShop/Views/Computer/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core

@model IPagedList<ComputerShop.Data.Models.Computer>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Computer List</h2>
<br>
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Computer Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Category Name</th>
        <th>Delete</th>
        <th>Update</th>
        <th>Details</th> 
    </tr>
    @foreach (var x in Model)
    {
    <tr>
        <th>@x.ComputerID</th>
        <td>@x.Name</td>
        <td>@x.Price</td>
        <td>@x.Stock</td>
        <td>@x.Category.CategoryName</td>
        <td><a href="/Computer/ComputerDelete?id=@x.ComputerID" class="btn btn-danger">Delete</a></td>
        <td><a href="/Computer/ComputerGet?id=@x.ComputerID" class="btn btn-success">Update</a></td>
        <td><a href="#" class="btn btn-info">Details</a></td>
    </tr>        
    }
</table>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new {page}))
<a href="/Computer/ComputerAdd/" class="btn btn-primary">New Computer</a>

ComputerShop/ComputerShop/Views/Default/Components/CategoryGetList/Default.cshtml
 @model IEnumerable<ComputerShop.Data.Models.Category>
 
 <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                    <ul class="nav navbar-nav nav_1">
                        @foreach (var item in Model)
                        {
                            //Seçtiğimiz category'nin id sinide bize verir
                            <li><a href="/Default/CategoryDetails/@item.CategoryID">@item.CategoryName</a></li>
                        }    
                    </ul>
                </div>

ComputerShop/ComputerShop/Views/Default/Components/ComputerGetList/Default.cshtml
@model IEnumerable<ComputerShop.Data.Models.Computer>

<div class="agile_top_brands_grids">
    @foreach (var item in Model)
    {
    <div class="col-md-3 top_brand_left" style="margin-bottom: 50px;">
        <div class="hover14 column">
            <div class="agile_top_brand_left_grid">
                <div class="agile_top_brand_left_grid1">
                    <figure>
                        <div class="snipcart-item block" >
                            <div class="snipcart-thumb">
                                <a href="single.html"><img style="width:250px; height:200px" title=" " alt=" " src="@item.ImageUrl" /></a>		
                                <p>@item.Name</p>
                                <h4>$@item.Price</h4><h6 style="color: red;">Stock:@item.Stock</h6>
                            </div>
                            <div class="snipcart-details top_brand_home_details">
                                <form action="#" method="post">
                                    <fieldset>
                                        <input type="hidden" name="cmd" value="_cart" />
                                        <input type="hidden" name="add" value="1" />
                                        <input type="hidden" name="business" value=" " />
                                        <input type="hidden" name="item_name" value="Fortune Sunflower Oil" />
                                        <input type="hidden" name="amount" value="7.99" />
                                        <input type="hidden" name="discount_amount" value="1.00" />
                                        <input type="hidden" name="currency_code" value="USD" />
                                        <input type="hidden" name="return" value=" " />
                                        <input type="hidden" name="cancel_return" value=" " />
                                        <input type="submit" name="submit" value="Add to cart" class="button" />
                                    </fieldset>
                                        
                                </form>
                        
                            </div>
                        </div>
                    </figure>
                </div>
            </div>
        </div>
    </div>
    }
    <div class="clearfix"> </div>
</div>

ComputerShop/ComputerShop/Views/Default/Components/ComputerListByCategory/Default.cshtml
@model IEnumerable<ComputerShop.Data.Models.Computer>

<div class="agile_top_brands_grids">
    @foreach (var item in Model)
    {
    <div class="col-md-3 top_brand_left" style="margin-bottom: 50px;">
        <div class="hover14 column">
            <div class="agile_top_brand_left_grid">
                <div class="agile_top_brand_left_grid1">
                    <figure>
                        <div class="snipcart-item block" >
                            <div class="snipcart-thumb">
                                <a href="single.html"><img style="width:250px; height:200px" title=" " alt=" " src="@item.ImageUrl" /></a>		
                                <p>@item.Name</p>
                                <h4>$@item.Price</h4><h6 style="color: red;">Stock:@item.Stock</h6>
                            </div>
                            <div class="snipcart-details top_brand_home_details">
                                <form action="#" method="post">
                                    <fieldset>
                                        <input type="hidden" name="cmd" value="_cart" />
                                        <input type="hidden" name="add" value="1" />
                                        <input type="hidden" name="business" value=" " />
                                        <input type="hidden" name="item_name" value="Fortune Sunflower Oil" />
                                        <input type="hidden" name="amount" value="7.99" />
                                        <input type="hidden" name="discount_amount" value="1.00" />
                                        <input type="hidden" name="currency_code" value="USD" />
                                        <input type="hidden" name="return" value=" " />
                                        <input type="hidden" name="cancel_return" value=" " />
                                        <input type="submit" name="submit" value="Add to cart" class="button" />
                                    </fieldset>
                                        
                                </form>
                        
                            </div>
                        </div>
                    </figure>
                </div>
            </div>
        </div>
    </div>
    }
    <div class="clearfix"> </div>
</div>

ComputerShop/ComputerShop/Views/Default/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

ComputerShop/ComputerShop/Views/Shared/_Layout.cshtml
<html lang="en">
<head>
  <title>Computer Shop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>


<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link active" href="/Category/Index/">Category</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/Computer/Index/">Computer</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/Chart/Index2">Column Chart</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/Chart/Index">Pie Chart</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/Chart/Statistics">Statistics</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/Login/LogOut">Log out</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container mt-3">
    @RenderBody()
</div>


</body>
</html>